[package]
name = "gleam"
version = "0.2.0"
license = "Apache-2.0"
authors = ["The Servo Project Developers"]
build = "build.rs"
documentation = "http://doc.servo.org/gleam/"
repository = "https://github.com/servo/gleam"
description = "Generated OpenGL bindings and wrapper for Servo."

[build-dependencies]
gl_generator = "0.2.0"
khronos_api = "0.0.8"

[dependencies]
libc="0.2"
