[package]
name = "gleam"
version = "0.1.0"
license = "Apache-2.0"
authors = ["The Servo Project Developers"]
build = "build.rs"
documentation = "http://doc.servo.org/gleam/"
description = "Generated OpenGL bindings and wrapper for Servo."

[build-dependencies]
gl_generator = "*"
khronos_api = "*"

[dependencies]
gl_common = "*"
libc="*"
