[package]
name = "gleam"
version = "0.1.17"
license = "Apache-2.0"
authors = ["The Servo Project Developers"]
build = "build.rs"
documentation = "http://doc.servo.org/gleam/"
description = "Generated OpenGL bindings and wrapper for Servo."

[build-dependencies]
gl_generator = "0.1.0"
khronos_api = "0.0.8"

[dependencies]
gl_common = "0.1"
libc="0.1"
